insert into region (id,code,local_code,region_name,continent,iso_country) values (1,'AD-02','02','Canillo','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (2,'AD-03','03','Encamp','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3,'AD-04','04','La Massana','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4,'AD-05','05','Ordino','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (5,'AD-06','06','Sant Julià de Lòria','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (6,'AD-07','07','Andorra la Vella','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (7,'AD-08','08','Escaldes-Engordany','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (8,'AD-U-A','U-A','(unassigned)','EU','AD');
insert into region (id,code,local_code,region_name,continent,iso_country) values (9,'AE-AJ','AJ','Ajman Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (10,'AE-AZ','AZ','Abu Dhabi Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (11,'AE-DU','DU','Dubai Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (12,'AE-FU','FU','Fujairah Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (13,'AE-RK','RK','Ras al-Khaimah Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (14,'AE-SH','SH','Sharjah Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (15,'AE-U-A','U-A','(unassigned)','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (16,'AE-UQ','UQ','Umm al-Quwain Emirate','AS','AE');
insert into region (id,code,local_code,region_name,continent,iso_country) values (17,'AF-BAL','BAL','Balkh Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (18,'AF-BAM','BAM','Bamiyan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (19,'AF-BDG','BDG','Badghis Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (20,'AF-BDS','BDS','Badakhshan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (21,'AF-BGL','BGL','Baghlan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4898,'AF-DAY','DAY','Daykundi Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (22,'AF-FRA','FRA','Farah Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (23,'AF-FYB','FYB','Faryab Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (24,'AF-GHA','GHA','Ghazni Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (25,'AF-GHO','GHO','Ghōr Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (26,'AF-HEL','HEL','Helmand Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (27,'AF-HER','HER','Herat Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (28,'AF-JOW','JOW','Jowzjan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (29,'AF-KAB','KAB','Kabul Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (30,'AF-KAN','KAN','Kandahar Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (31,'AF-KAP','KAP','Kapisa Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (32,'AF-KDZ','KDZ','Kunduz Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (33,'AF-KHO','KHO','Khost Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (34,'AF-KNR','KNR','Kunar Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (35,'AF-LAG','LAG','Laghman Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (36,'AF-LOW','LOW','Logar Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (37,'AF-NAN','NAN','Nangarhar Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (38,'AF-NIM','NIM','Nimruz Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (39,'AF-NUR','NUR','Nurestan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (40,'AF-ORU','ORU','Orūzgān Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4899,'AF-PAN','PAN','Panjshir Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (41,'AF-PAR','PAR','Parwan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (42,'AF-PIA','PIA','Paktia Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (43,'AF-PKA','PKA','Paktika Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (44,'AF-SAM','SAM','Samangan Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (45,'AF-SAR','SAR','Sar-e Pol Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (46,'AF-TAK','TAK','Takhar Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (47,'AF-U-A','U-A','(unassigned)','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (48,'AF-WAR','WAR','Wardak Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (49,'AF-ZAB','ZAB','Zabul Province','AS','AF');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4769,'AG-03','03','Saint George','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4770,'AG-04','04','Saint John','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4771,'AG-05','05','Saint Mary','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4772,'AG-06','06','Saint Paul','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4773,'AG-07','07','Saint Peter','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4774,'AG-08','08','Saint Philip','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (4775,'AG-10','09','Barbuda','NA','AG');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3870,'US-AK','AK','Alaska','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3871,'US-AL','AL','Alabama','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3873,'US-AR','AR','Arkansas','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3875,'US-AZ','AZ','Arizona','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3876,'US-CA','CA','California','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3877,'US-CO','CO','Colorado','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3878,'US-CT','CT','Connecticut','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3879,'US-DC','DC','District of Columbia','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3880,'US-DE','DE','Delaware','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3881,'US-FL','FL','Florida','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3882,'US-GA','GA','Georgia','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3884,'US-HI','HI','Hawaii','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3885,'US-IA','IA','Iowa','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3886,'US-ID','ID','Idaho','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3887,'US-IL','IL','Illinois','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3888,'US-IN','IN','Indiana','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3889,'US-KS','KS','Kansas','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3890,'US-KY','KY','Kentucky','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3891,'US-LA','LA','Louisiana','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3892,'US-MA','MA','Massachusetts','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3893,'US-MD','MD','Maryland','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3894,'US-ME','ME','Maine','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3895,'US-MI','MI','Michigan','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3896,'US-MN','MN','Minnesota','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3897,'US-MO','MO','Missouri','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3899,'US-MS','MS','Mississippi','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3900,'US-MT','MT','Montana','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3901,'US-NC','NC','North Carolina','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3902,'US-ND','ND','North Dakota','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3903,'US-NE','NE','Nebraska','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3904,'US-NH','NH','New Hampshire','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3905,'US-NJ','NJ','New Jersey','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3906,'US-NM','NM','New Mexico','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3907,'US-NV','NV','Nevada','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3908,'US-NY','NY','New York','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3909,'US-OH','OH','Ohio','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3910,'US-OK','OK','Oklahoma','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3911,'US-OR','OR','Oregon','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3912,'US-PA','PA','Pennsylvania','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3914,'US-RI','RI','Rhode Island','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3915,'US-SC','SC','South Carolina','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3916,'US-SD','SD','South Dakota','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3917,'US-TN','TN','Tennessee','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3918,'US-TX','TX','Texas','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3919,'US-U-A','U-A','(unassigned)','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3921,'US-UT','UT','Utah','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3922,'US-VA','VA','Virginia','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3924,'US-VT','VT','Vermont','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3925,'US-WA','WA','Washington','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3926,'US-WI','WI','Wisconsin','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3927,'US-WV','WV','West Virginia','NA','US');
insert into region (id,code,local_code,region_name,continent,iso_country) values (3928,'US-WY','WY','Wyoming','NA','US');


insert into country(id,code,country_name,continent) values (1,'AD','Andorra','EU');
insert into country(id,code,country_name,continent) values (2,'AE','United Arab Emirates','AS');
insert into country(id,code,country_name,continent) values (3,'AF','Afghanistan','AS');
insert into country(id,code,country_name,continent) values (4,'AG','Antigua and Barbuda','NA');
insert into country(id,code,country_name,continent) values (5,'AI','Anguilla','NA');
insert into country(id,code,country_name,continent) values (6,'AL','Albania','EU');
insert into country(id,code,country_name,continent) values (7,'AM','Armenia','AS');
insert into country(id,code,country_name,continent) values (8,'AN','Netherlands Antilles','NA');
insert into country(id,code,country_name,continent) values (9,'AO','Angola','AF');
insert into country(id,code,country_name,continent) values (10,'AQ','Antarctica','AN');
insert into country(id,code,country_name,continent) values (11,'AR','Argentina','SA');
insert into country(id,code,country_name,continent) values (12,'AS','American Samoa','OC');
insert into country(id,code,country_name,continent) values (13,'AT','Austria','EU');
insert into country(id,code,country_name,continent) values (14,'AU','Australia','OC');
insert into country(id,code,country_name,continent) values (15,'AW','Aruba','NA');
insert into country(id,code,country_name,continent) values (16,'AZ','Azerbaijan','AS');
insert into country(id,code,country_name,continent) values (17,'BA','Bosnia and Herzegovina','EU');
insert into country(id,code,country_name,continent) values (18,'BB','Barbados','NA');
insert into country(id,code,country_name,continent) values (19,'BD','Bangladesh','AS');
insert into country(id,code,country_name,continent) values (20,'BE','Belgium','EU');
insert into country(id,code,country_name,continent) values (21,'BF','Burkina Faso','AF');
insert into country(id,code,country_name,continent) values (22,'BG','Bulgaria','EU');
insert into country(id,code,country_name,continent) values (23,'BH','Bahrain','AS');
insert into country(id,code,country_name,continent) values (24,'BI','Burundi','AF');
insert into country(id,code,country_name,continent) values (25,'BJ','Benin','AF');
insert into country(id,code,country_name,continent) values (245,'BL','Saint Barthélemy','NA');
insert into country(id,code,country_name,continent) values (26,'BM','Bermuda','NA');
insert into country(id,code,country_name,continent) values (27,'BN','Brunei','AS');
insert into country(id,code,country_name,continent) values (28,'BO','Bolivia','SA');
insert into country(id,code,country_name,continent) values (29,'BR','Brazil','SA');
insert into country(id,code,country_name,continent) values (30,'BS','Bahamas','NA');
insert into country(id,code,country_name,continent) values (31,'BT','Bhutan','AS');
insert into country(id,code,country_name,continent) values (32,'BW','Botswana','AF');
insert into country(id,code,country_name,continent) values (33,'BY','Belarus','EU');
insert into country(id,code,country_name,continent) values (34,'BZ','Belize','NA');
insert into country(id,code,country_name,continent) values (35,'CA','Canada','NA');
insert into country(id,code,country_name,continent) values (36,'CC','Cocos (Keeling) Islands','AS');
insert into country(id,code,country_name,continent) values (37,'CD','Congo (Kinshasa)','AF');
insert into country(id,code,country_name,continent) values (38,'CF','Central African Republic','AF');
insert into country(id,code,country_name,continent) values (39,'CG','Congo (Brazzaville)','AF');
insert into country(id,code,country_name,continent) values (40,'CH','Switzerland','EU');
insert into country(id,code,country_name,continent) values (41,'CI','Côte d''Ivoire','AF');
insert into country(id,code,country_name,continent) values (42,'CK','Cook Islands','OC');
insert into country(id,code,country_name,continent) values (43,'CL','Chile','SA');
insert into country(id,code,country_name,continent) values (44,'CM','Cameroon','AF');
insert into country(id,code,country_name,continent) values (45,'CN','China','AS');
insert into country(id,code,country_name,continent) values (46,'CO','Colombia','SA');
insert into country(id,code,country_name,continent) values (47,'CR','Costa Rica','NA');
insert into country(id,code,country_name,continent) values (49,'CU','Cuba','NA');
insert into country(id,code,country_name,continent) values (50,'CV','Cape Verde','AF');
insert into country(id,code,country_name,continent) values (51,'CX','Christmas Island','AS');
insert into country(id,code,country_name,continent) values (52,'CY','Cyprus','AS');
insert into country(id,code,country_name,continent) values (53,'CZ','Czech Republic','EU');
insert into country(id,code,country_name,continent) values (54,'DE','Germany','EU');
insert into country(id,code,country_name,continent) values (55,'DJ','Djibouti','AF');
insert into country(id,code,country_name,continent) values (56,'DK','Denmark','EU');
insert into country(id,code,country_name,continent) values (57,'DM','Dominica','NA');
insert into country(id,code,country_name,continent) values (58,'DO','Dominican Republic','NA');
insert into country(id,code,country_name,continent) values (59,'DZ','Algeria','AF');
insert into country(id,code,country_name,continent) values (60,'EC','Ecuador','SA');
insert into country(id,code,country_name,continent) values (61,'EE','Estonia','EU');
insert into country(id,code,country_name,continent) values (62,'EG','Egypt','AF');
insert into country(id,code,country_name,continent) values (63,'EH','Western Sahara','AF');
insert into country(id,code,country_name,continent) values (64,'ER','Eritrea','AF');
insert into country(id,code,country_name,continent) values (65,'ES','Spain','EU');
insert into country(id,code,country_name,continent) values (66,'ET','Ethiopia','AF');
insert into country(id,code,country_name,continent) values (67,'FI','Finland','EU');
insert into country(id,code,country_name,continent) values (68,'FJ','Fiji','OC');
insert into country(id,code,country_name,continent) values (69,'FK','Falkland Islands','SA');
insert into country(id,code,country_name,continent) values (70,'FM','Micronesia','OC');
insert into country(id,code,country_name,continent) values (71,'FO','Faroe Islands','EU');
insert into country(id,code,country_name,continent) values (72,'FR','France','EU');
insert into country(id,code,country_name,continent) values (73,'GA','Gabon','AF');
insert into country(id,code,country_name,continent) values (74,'GB','United Kingdom','EU');
insert into country(id,code,country_name,continent) values (75,'GD','Grenada','NA');
insert into country(id,code,country_name,continent) values (76,'GE','Georgia','AS');
insert into country(id,code,country_name,continent) values (77,'GF','French Guiana','SA');
insert into country(id,code,country_name,continent) values (78,'GG','Guernsey','EU');
insert into country(id,code,country_name,continent) values (79,'GH','Ghana','AF');
insert into country(id,code,country_name,continent) values (80,'GI','Gibraltar','EU');
insert into country(id,code,country_name,continent) values (81,'GL','Greenland','NA');
insert into country(id,code,country_name,continent) values (82,'GM','Gambia','AF');
insert into country(id,code,country_name,continent) values (83,'GN','Guinea','AF');
insert into country(id,code,country_name,continent) values (84,'GP','Guadeloupe','NA');
insert into country(id,code,country_name,continent) values (85,'GQ','Equatorial Guinea','AF');
insert into country(id,code,country_name,continent) values (86,'GR','Greece','EU');
insert into country(id,code,country_name,continent) values (87,'GS','South Georgia and the South Sandwich Islands','AN');
insert into country(id,code,country_name,continent) values (88,'GT','Guatemala','NA');
insert into country(id,code,country_name,continent) values (89,'GU','Guam','OC');
insert into country(id,code,country_name,continent) values (90,'GW','Guinea-Bissau','AF');
insert into country(id,code,country_name,continent) values (91,'GY','Guyana','SA');
insert into country(id,code,country_name,continent) values (92,'HK','Hong Kong','AS');
insert into country(id,code,country_name,continent) values (93,'HN','Honduras','NA');
insert into country(id,code,country_name,continent) values (94,'HR','Croatia','EU');
insert into country(id,code,country_name,continent) values (95,'HT','Haiti','NA');
insert into country(id,code,country_name,continent) values (96,'HU','Hungary','EU');
insert into country(id,code,country_name,continent) values (97,'ID','Indonesia','AS');
insert into country(id,code,country_name,continent) values (98,'IE','Ireland','EU');
insert into country(id,code,country_name,continent) values (99,'IL','Israel','AS');
insert into country(id,code,country_name,continent) values (100,'IM','Isle of Man','EU');
insert into country(id,code,country_name,continent) values (101,'IN','India','AS');
insert into country(id,code,country_name,continent) values (102,'IO','British Indian Ocean Territory','AS');
insert into country(id,code,country_name,continent) values (103,'IQ','Iraq','AS');
insert into country(id,code,country_name,continent) values (104,'IR','Iran','AS');
insert into country(id,code,country_name,continent) values (105,'IS','Iceland','EU');
insert into country(id,code,country_name,continent) values (107,'JE','Jersey','EU');
insert into country(id,code,country_name,continent) values (106,'IT','Italy','EU');
insert into country(id,code,country_name,continent) values (108,'JM','Jamaica','NA');
insert into country(id,code,country_name,continent) values (109,'JO','Jordan','AS');
insert into country(id,code,country_name,continent) values (110,'JP','Japan','AS');
insert into country(id,code,country_name,continent) values (111,'KE','Kenya','AF');
insert into country(id,code,country_name,continent) values (112,'KG','Kyrgyzstan','AS');
insert into country(id,code,country_name,continent) values (113,'KH','Cambodia','AS');
insert into country(id,code,country_name,continent) values (114,'KI','Kiribati','OC');
insert into country(id,code,country_name,continent) values (115,'KM','Comoros','AF');
insert into country(id,code,country_name,continent) values (116,'KN','Saint Kitts and Nevis','NA');
insert into country(id,code,country_name,continent) values (117,'KP','North Korea','AS');
insert into country(id,code,country_name,continent) values (118,'KR','South Korea','AS');
insert into country(id,code,country_name,continent) values (243,'KS','Kosovo','EU');
insert into country(id,code,country_name,continent) values (119,'KW','Kuwait','AS');
insert into country(id,code,country_name,continent) values (120,'KY','Cayman Islands','NA');
insert into country(id,code,country_name,continent) values (121,'KZ','Kazakhstan','AS');
insert into country(id,code,country_name,continent) values (122,'LA','Laos','AS');
insert into country(id,code,country_name,continent) values (123,'LB','Lebanon','AS');
insert into country(id,code,country_name,continent) values (124,'LC','Saint Lucia','NA');
insert into country(id,code,country_name,continent) values (125,'LI','Liechtenstein','EU');
insert into country(id,code,country_name,continent) values (126,'LK','Sri Lanka','AS');
insert into country(id,code,country_name,continent) values (127,'LR','Liberia','AF');
insert into country(id,code,country_name,continent) values (128,'LS','Lesotho','AF');
insert into country(id,code,country_name,continent) values (129,'LT','Lithuania','EU');
insert into country(id,code,country_name,continent) values (130,'LU','Luxembourg','EU');
insert into country(id,code,country_name,continent) values (131,'LV','Latvia','EU');
insert into country(id,code,country_name,continent) values (132,'LY','Libya','AF');
insert into country(id,code,country_name,continent) values (133,'MA','Morocco','AF');
insert into country(id,code,country_name,continent) values (134,'MC','Monaco','EU');
insert into country(id,code,country_name,continent) values (135,'MD','Moldova','EU');
insert into country(id,code,country_name,continent) values (136,'ME','Montenegro','EU');
insert into country(id,code,country_name,continent) values (244,'MF','Saint Martin','NA');
insert into country(id,code,country_name,continent) values (137,'MG','Madagascar','AF');
insert into country(id,code,country_name,continent) values (138,'MH','Marshall Islands','OC');
insert into country(id,code,country_name,continent) values (139,'MK','Macedonia','EU');
insert into country(id,code,country_name,continent) values (140,'ML','Mali','AF');
insert into country(id,code,country_name,continent) values (141,'MM','Burma','AS');
insert into country(id,code,country_name,continent) values (142,'MN','Mongolia','AS');
insert into country(id,code,country_name,continent) values (143,'MO','Macau','AS');
insert into country(id,code,country_name,continent) values (144,'MP','Northern Mariana Islands','OC');
insert into country(id,code,country_name,continent) values (145,'MQ','Martinique','NA');
insert into country(id,code,country_name,continent) values (146,'MR','Mauritania','AF');
insert into country(id,code,country_name,continent) values (147,'MS','Montserrat','NA');
insert into country(id,code,country_name,continent) values (148,'MT','Malta','EU');
insert into country(id,code,country_name,continent) values (149,'MU','Mauritius','AF');
insert into country(id,code,country_name,continent) values (150,'MV','Maldives','AS');
insert into country(id,code,country_name,continent) values (151,'MW','Malawi','AF');
insert into country(id,code,country_name,continent) values (152,'MX','Mexico','NA');
insert into country(id,code,country_name,continent) values (153,'MY','Malaysia','AS');
insert into country(id,code,country_name,continent) values (154,'MZ','Mozambique','AF');
insert into country(id,code,country_name,continent) values (155,'NA','Namibia','AF');
insert into country(id,code,country_name,continent) values (156,'NC','New Caledonia','OC');
insert into country(id,code,country_name,continent) values (157,'NE','Niger','AF');
insert into country(id,code,country_name,continent) values (158,'NF','Norfolk Island','OC');
insert into country(id,code,country_name,continent) values (159,'NG','Nigeria','AF');
insert into country(id,code,country_name,continent) values (160,'NI','Nicaragua','NA');
insert into country(id,code,country_name,continent) values (161,'NL','Netherlands','EU');
insert into country(id,code,country_name,continent) values (162,'NO','Norway','EU');
insert into country(id,code,country_name,continent) values (163,'NP','Nepal','AS');
insert into country(id,code,country_name,continent) values (164,'NR','Nauru','OC');
insert into country(id,code,country_name,continent) values (165,'NU','Niue','OC');
insert into country(id,code,country_name,continent) values (166,'NZ','New Zealand','OC');
insert into country(id,code,country_name,continent) values (167,'OM','Oman','AS');
insert into country(id,code,country_name,continent) values (168,'PA','Panama','NA');
insert into country(id,code,country_name,continent) values (169,'PE','Perú','SA');
insert into country(id,code,country_name,continent) values (170,'PF','French Polynesia','OC');
insert into country(id,code,country_name,continent) values (171,'PG','Papua New Guinea','OC');
insert into country(id,code,country_name,continent) values (172,'PH','Philippines','AS');
insert into country(id,code,country_name,continent) values (173,'PK','Pakistan','AS');
insert into country(id,code,country_name,continent) values (174,'PL','Poland','EU');
insert into country(id,code,country_name,continent) values (175,'PM','Saint Pierre and Miquelon','NA');
insert into country(id,code,country_name,continent) values (176,'PN','Pitcairn','OC');
insert into country(id,code,country_name,continent) values (177,'PR','Puerto Rico','NA');
insert into country(id,code,country_name,continent) values (178,'PS','Palestinian Territory','AS');
insert into country(id,code,country_name,continent) values (179,'PT','Portugal','EU');
insert into country(id,code,country_name,continent) values (180,'PW','Palau','OC');
insert into country(id,code,country_name,continent) values (181,'PY','Paraguay','SA');
insert into country(id,code,country_name,continent) values (182,'QA','Qatar','AS');
insert into country(id,code,country_name,continent) values (183,'RE','Réunion','AF');
insert into country(id,code,country_name,continent) values (184,'RO','Romania','EU');
insert into country(id,code,country_name,continent) values (185,'RS','Serbia','EU');
insert into country(id,code,country_name,continent) values (186,'RU','Russia','EU');
insert into country(id,code,country_name,continent) values (187,'RW','Rwanda','AF');
insert into country(id,code,country_name,continent) values (188,'SA','Saudi Arabia','AS');
insert into country(id,code,country_name,continent) values (189,'SB','Solomon Islands','OC');
insert into country(id,code,country_name,continent) values (190,'SC','Seychelles','AF');
insert into country(id,code,country_name,continent) values (191,'SD','Sudan','AF');
insert into country(id,code,country_name,continent) values (192,'SE','Sweden','EU');
insert into country(id,code,country_name,continent) values (193,'SG','Singapore','AS');
insert into country(id,code,country_name,continent) values (194,'SH','Saint Helena','AF');
insert into country(id,code,country_name,continent) values (195,'SI','Slovenia','EU');
insert into country(id,code,country_name,continent) values (197,'SK','Slovakia','EU');
insert into country(id,code,country_name,continent) values (198,'SL','Sierra Leone','AF');
insert into country(id,code,country_name,continent) values (199,'SM','San Marino','EU');
insert into country(id,code,country_name,continent) values (200,'SN','Senegal','AF');
insert into country(id,code,country_name,continent) values (201,'SO','Somalia','AF');
insert into country(id,code,country_name,continent) values (202,'SR','Suriname','SA');
insert into country(id,code,country_name,continent) values (247,'SS','South Sudan','AF');
insert into country(id,code,country_name,continent) values (203,'ST','São Tomé and Principe','AF');
insert into country(id,code,country_name,continent) values (204,'SV','El Salvador','NA');
insert into country(id,code,country_name,continent) values (205,'SY','Syria','AS');
insert into country(id,code,country_name,continent) values (206,'SZ','Swaziland','AF');
insert into country(id,code,country_name,continent) values (207,'TC','Turks and Caicos Islands','NA');
insert into country(id,code,country_name,continent) values (208,'TD','Chad','AF');
insert into country(id,code,country_name,continent) values (209,'TF','French Southern Territories','AN');
insert into country(id,code,country_name,continent) values (210,'TG','Togo','AF');
insert into country(id,code,country_name,continent) values (211,'TH','Thailand','AS');
insert into country(id,code,country_name,continent) values (212,'TJ','Tajikistan','AS');
insert into country(id,code,country_name,continent) values (213,'TK','Tokelau','OC');
insert into country(id,code,country_name,continent) values (214,'TL','Timor-Leste','AS');
insert into country(id,code,country_name,continent) values (216,'TN','Tunisia','AF');
insert into country(id,code,country_name,continent) values (215,'TM','Turkmenistan','AS');
insert into country(id,code,country_name,continent) values (217,'TO','Tonga','OC');
insert into country(id,code,country_name,continent) values (218,'TR','Turkey','AS');
insert into country(id,code,country_name,continent) values (219,'TT','Trinidad and Tobago','NA');
insert into country(id,code,country_name,continent) values (220,'TV','Tuvalu','OC');
insert into country(id,code,country_name,continent) values (221,'TW','Taiwan','AS');
insert into country(id,code,country_name,continent) values (222,'TZ','Tanzania','AF');
insert into country(id,code,country_name,continent) values (223,'UA','Ukraine','EU');
insert into country(id,code,country_name,continent) values (224,'UG','Uganda','AF');
insert into country(id,code,country_name,continent) values (225,'UM','United States Minor Outlying Islands','OC');
insert into country(id,code,country_name,continent) values (226,'US','United States','NA');
insert into country(id,code,country_name,continent) values (227,'UY','Uruguay','SA');
insert into country(id,code,country_name,continent) values (228,'UZ','Uzbekistan','AS');
insert into country(id,code,country_name,continent) values (246,'VA','Vatican City','EU');
insert into country(id,code,country_name,continent) values (229,'VC','Saint Vincent and the Grenadines','NA');
insert into country(id,code,country_name,continent) values (230,'VE','Venezuela','SA');
insert into country(id,code,country_name,continent) values (231,'VG','British Virgin Islands','NA');
insert into country(id,code,country_name,continent) values (232,'VI','U.S. Virgin Islands','NA');
insert into country(id,code,country_name,continent) values (233,'VN','Vietnam','AS');
insert into country(id,code,country_name,continent) values (234,'VU','Vanuatu','OC');
insert into country(id,code,country_name,continent) values (235,'WF','Wallis and Futuna','OC');
insert into country(id,code,country_name,continent) values (236,'WS','Samoa','OC');
insert into country(id,code,country_name,continent) values (237,'YE','Yemen','AS');
insert into country(id,code,country_name,continent) values (238,'YT','Mayotte','AF');
insert into country(id,code,country_name,continent) values (239,'ZA','South Africa','AF');
insert into country(id,code,country_name,continent) values (240,'ZM','Zambia','AF');
insert into country(id,code,country_name,continent) values (241,'ZW','Zimbabwe','AF');

